### ISSUE TITLE
confusing sources in py.test ?

### ISSUE THREAD

**Issue by hszcg** [amscanne/huptime#21]
hi, just wondering that why we have a confusing sources in py.test ?

I saw you import it, but it's unclear that what's inside actually
https://github.com/amscanne/huptime/blob/master/py.test#L2652

Could you please make it more transparent?

**Comment by amscanne** [comment]
This is a self-contained py.test script in order to reduce dependencies. To see how it was generated, see the standalone script section in this document: http://pytest.org/latest/goodpractises.html

If this is about running unknown code, please feel free to verify the blob is as described. Just change the script to print sources and exit.

**Comment by hszcg** [comment]
thanks @amscanne , much clear now :)

maybe you could add some comments inline if it's convenient?
